/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.traderepublic.quotessystem;

import com.traderepublic.quotessystem.clients.ProvidersClient;
import com.traderepublic.quotessystem.clients.ProvidersSessionHandler;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.reactive.socket.client.WebSocketClient;

@SpringBootApplication
public class App {

    private static Logger logger = LoggerFactory.getLogger(App.class);

    @Autowired
    @Qualifier("quotesClient")
    private WebSocketClient quotesClient;

    @Autowired
    @Qualifier("instrumentsClient")
    private WebSocketClient instrumentsClient;

    public static void main(String[] args) {
        logger.info("Hello there!");
        SpringApplication.run(App.class, args);
    }
}
